[package]
name = "Lox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proc-macro2 = { version = "1.0.78", features = [] }
log = "0.4.20"
paste = "1.0.14"
